name: build-windows
on:
  workflow_dispatch:
    inputs:
      windows_version:
        type: choice
        description: Select Windows version
        default: windows-2019
        required: true
        options:
          - windows-latest
          - windows-2025
          - windows-2022
          - windows-2019

jobs:
  build-windows:
    runs-on: ${{ github.event.inputs.windows_version }}
    steps:

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Build externals on Windows
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release

    - name: upload windows package
      uses: actions/upload-artifact@v4
      with:
        name: dao-max-pd
        path: |
            externals
            help
            media
            patchers
            LICENSE.md
            README.md
