name: build-package
on:
  workflow_dispatch:
    inputs:
      macos_version:
        type: choice
        description: Select MacOS version
        default: macos-14
        required: true
        options:
          - macos-latest
          - macos-15
          - macos-14
          - macos-13

      windows_version:
        type: choice
        description: Select Windows version
        default: windows-2019
        required: true
        options:
          - windows-latest
          - windows-2025
          - windows-2022
          - windows-2019

      linux_version:
        type: choice
        description: Select Linux version
        default: ubuntu-22.04
        required: true
        options:
          - ubuntu-latest
          - ubuntu-24.04
          - ubuntu-22.04

jobs:
  build-windows:
    runs-on: ${{ github.event.inputs.windows_version }}
    steps:

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Build externals on Windows
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release

    - name: Upload win64 externals
      uses: actions/upload-artifact@v4
      with:
        name: win64-externals
        path: |
          externals/*.mxe64
          externals/pd/**/*.dll
        retention-days: 1

  build-macos:
    runs-on: ${{ github.event.inputs.macos_version }}
    needs: [build-windows]
    steps:

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Build externals
      run: |
        mkdir -p build
        cd build
        cmake .. -GXcode
        cmake --build . --config Release

    - name: Upload macOS externals
      uses: actions/upload-artifact@v4
      with:
        name: macos-externals
        path: |
          externals/*.mxo
          externals/pd/**/*.pd_darwin
        retention-days: 1

  build-linux:
    runs-on: ${{ github.event.inputs.linux_version }}
    needs: [build-macos]
    steps:

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Build externals
      run: |
        mkdir -p build
        cd build
        cmake ..
        cmake --build . --config Release

    - name: Upload Linux externals
      uses: actions/upload-artifact@v4
      with:
        name: linux-externals
        path: externals/pd/**/*.pd_linux
        retention-days: 1

  build-package:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:

    - uses: actions/checkout@v4

    - name: Download Windows externals
      uses: actions/download-artifact@v4
      with:
        name: win64-externals
        path: externals
        merge-multiple: true

    - name: Download MacOS externals
      uses: actions/download-artifact@v4
      with:
        name: macos-externals
        path: externals
        merge-multiple: true

    - name: Download Linux externals
      uses: actions/download-artifact@v4
      with:
        name: linux-externals
        path: externals/pd
        merge-multiple: true

    - uses: actions/upload-artifact@v4
      with:
        name: dao-max-pd
        path: |
            externals
            help
            media
            patchers
            LICENSE.md
            README.md

